server:
  port: 8084
  servlet:
    context-path: 

spring:
  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:15490/railway
    username: postgres
    password: mctNKuNiSneLFXCqgnSONsjXoRNFCqNo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 104857600  # 100MB
      max-request-size: 104857600  # 100MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO

# JWT Configuration - Must match auth-service signerKey
jwt:
  signerKey: QVHfEyXEd7KG4eUfYAWOUvuPjlufU3vImJ0MEialEhHoQPjB6wZTL6Ma9XLnKaYn

# File upload configuration
file:
  upload:
    max-size: 104857600  # 100MB
    allowed-audio-types: audio/mpeg,audio/mp3,audio/wav,audio/wave,audio/x-wav,audio/mp4,audio/m4a,audio/x-m4a
    allowed-image-types: image/jpeg,image/jpg,image/png
    allowed-sheet-music-types: application/pdf,application/xml,text/xml,audio/midi,audio/x-midi,audio/mid

# AWS S3 Configuration
aws:
  s3:
    enabled: true
    bucket-name: mutrapro-dev-files
    region: ap-southeast-1
    access-key: AKIAZ24ITCMNFIY2Z3VX
    secret-key: 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

# Outbox Configuration
app:
  outbox:
    max-retries: 3
  event-topics:
    mappings:
      file.uploaded: file-uploaded
      request.assigned: request-events

# Project Service Configuration
project:
  service:
    base-url: http://localhost:8082

# Identity Service Configuration
identity:
  service:
    base-url: http://localhost:8081