apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: mutrapro
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP
  - name: websocket
    port: 8088
    targetPort: 8088
    protocol: TCP
  selector:
    app: chat-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

