apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: mutrapro
  labels:
    app: feedback-service
spec:
  selector:
    app: feedback-service
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
  type: ClusterIP
