apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: mutrapro
  labels:
    app: project-service
spec:
  selector:
    app: project-service
  ports:
  - name: http
    port: 80
    targetPort: 8086
    protocol: TCP
  type: ClusterIP
