apiVersion: v1
kind: Service
metadata:
  name: quotation-service
  namespace: mutrapro
  labels:
    app: quotation-service
spec:
  selector:
    app: quotation-service
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP
  type: ClusterIP
