apiVersion: v1
kind: Service
metadata:
  name: request-service
  namespace: mutrapro
  labels:
    app: request-service
spec:
  selector:
    app: request-service
  ports:
  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP
  type: ClusterIP

