apiVersion: v1
kind: Service
metadata:
  name: revision-service
  namespace: mutrapro
  labels:
    app: revision-service
spec:
  selector:
    app: revision-service
  ports:
  - name: http
    port: 8089
    targetPort: 8089
    protocol: TCP
  type: ClusterIP
