apiVersion: v1
kind: Service
metadata:
  name: specialist-service
  namespace: mutrapro
  labels:
    app: specialist-service
spec:
  selector:
    app: specialist-service
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
  type: ClusterIP
