apiVersion: v1
kind: Service
metadata:
  name: studio-service
  namespace: mutrapro
  labels:
    app: studio-service
spec:
  selector:
    app: studio-service
  ports:
  - name: http
    port: 8091
    targetPort: 8091
    protocol: TCP
  type: ClusterIP
